const categories = [
  "Accessories",
  "Athletic",
  "Badminton",
  "Bathroom",
  "Body Care",
  "Car Accessories",
  "Cricket",
  "Chess",
  "Hair Care",
  "Home Appliances",
  "Men's Wear",
  "Men's Footwear",
  "Men Athletic",
  "Men's Accessories",
  "Face Care",
  "Football",
  "Fitness",
  "Skates",
  "Kitchen",
  "Sports",
  "Showpiece",
];

export default categories;
