const searchTOfProduct = [
  "Ball",
  "Hand Grip",
  "Abs Roller",
  "Football Shoes",
  "Volleyball",
  "Football Socks",
  "Badminton Racket",
  "Fitness Gloves",
  "Resistance Band",
  "Disc Cones",
  "Marking Cones",
  "Massage Roller",
  "Kettle Bell",
  "Resistance Tube",
  "Wrist Support",
  "Inline Skates",
  "Shuttlecock",
  "Dumbbell",
  "Cricket Stumps",
  "Gym Ball",
  "Quad Roller Skates",
  "Ab Roller",
  "Skipping Rope",
  "Protein Shaker",
  "Chess Set",
  "Chess Coin",
  "Yoga Mat",
  "Water Bottle",
  "Carrom Coins",
  "Knee Support",
  "Chess Pieces",
  "Supporter",
  "Elbow Support",
  "Skating Protective Set",
  "Throwing Discs",
  "Hand Gripper",
  "Weighing Scale",
  "Abdominal Guard",
  "Face Scrub",
  "Face Cream",
  "Face Moisturizer",
  "Bleach",
  "Face Wash",
  "Sunscreen",
  "Face Lotion",
];
export default searchTOfProduct;
