const searchTOfProduct = [
  "Abs Exercise Equipment",
  "Ankle Support",
  "Badminton Ball",
  "Badminton Ball",
  "Badminton Racket",
  "Body Lotion",
  "Body Wash",
  "Cap",
  "Chess Clock",
  "Chess Pieces",
  "Chess Set",
  "Chessboard",
  "College Bag",
  "Disc Cone",
  "Exercise Ball",
  "Face Cream",
  "Face Scrub",
  "Face Wash",
  "Fitness Gloves",
  "Good Luck",
  "Holder For Bathroom",
  "Kettlebell",
  "Keychain",
  "Knee Support",
  "Lanterns/Candle Holders",
  "Marker Cones",
  "Massage Roller",
  "Mini Sculptures",
  "Protein Shaker",
  "Resistance Band",
  "Shampoo",
  "Shuttlecock",
  "Skipping Rope",
  "Soap Stand",
  "Sport A-L Socks",
  "Sport K-L Socks",
  "Strengthener",
  "Tooth Brush Holder",
  "Tradition Showpiece",
  "Vases",
  "Wall Art",
  "Wallets",
  "Weight Machine For Body",
  "Wrist Band",
  "Yoga Mat",
];
export default searchTOfProduct;
